sysrepo BUGFIX segfault with non-existing RPC
sysrepo/sysrepo pull request #2117
Opened 2020-09-01 10:31 UTC by syyyr

Fixes part of #2115

2020-09-01 17:19 UTC, jktjkt approved these changes

2020-09-02 12:48 UTC, michalvasko commented
Uh, sorry, I have fixed it before looking at this PR. So just remove the fix please, the test can be merged.

2020-09-02 12:49 UTC, michalvasko requested changes

2020-09-02 12:49 UTC, michalvasko commented on src/sysrepo.c
> +        }
Fixed already.

2020-09-02 12:49 UTC, michalvasko commented on tests/test_rpc_action.c
> +
Formatting - extra line.

2020-09-02 13:06 UTC, syyyr commented on tests/test_rpc_action.c
> +
Done

2020-09-02 13:07 UTC, syyyr commented on src/sysrepo.c
> +        }
Done

2020-09-02 13:07 UTC, syyyr commented
All done

2020-09-02 13:32 UTC, michalvasko approved these changes

2020-09-02 13:32 UTC, michalvasko commented
Fine, thanks.

2020-09-02 13:33 UTC, merged