Change some typedef structs into normal structs
sysrepo/sysrepo pull request #2566
Opened 2021-09-06 21:30 UTC by syyyr

Hi, while working on my C++ wrapper for sysrepo, I found out that some of the structs are defined as typedefs. This means that you can't forward declare them. I think this change should not have an effect on existing code, but I'm not sure. What do you think?

I'm creating this as a draft, because I'm not sure what structs I'll have to change.

2021-09-06 23:19 UTC, syyyr commented
Ideally, I would like all structs to be in the C "struct namespace" and then possibly in the global "typedef" namespace.

2021-09-07 06:28 UTC, michalvasko requested changes

2021-09-07 06:28 UTC, michalvasko commented on src/sysrepo_types.h
> +} ;
Extra space.

2021-09-07 06:29 UTC, michalvasko commented
I have no problem with the change and any like this. However, please rebase your branch to the current `devel`, you seem to have quite an old revision.

2021-09-07 09:04 UTC, syyyr commented on src/sysrepo_types.h
> +} ;
done

2021-09-07 09:10 UTC, syyyr commented
>I have no problem with the change and any like this.

Great! I changed all (or most) of them.

>However, please rebase your branch to the current devel, you seem to have quite an old revision.

The patch is now rebased to devel.

2021-09-07 09:28 UTC, michalvasko approved these changes

2021-09-07 09:31 UTC, merged