WIP: Updated Debian packaging
sysrepo/sysrepo pull request #2673
Opened 2021-12-12 20:58 UTC by oerdnj

WIP: This needs better commit message and better comment here.

2021-12-13 08:21 UTC, michalvasko requested changes

2021-12-13 08:21 UTC, michalvasko commented on distro/pkg/deb/copyright
> +License: Apache-2.0
The license of the whole project was changed to BSD-3-Clause.

2021-12-13 08:21 UTC, michalvasko commented on distro/pkg/deb/sysrepo-plugind.lintian-overrides
> +sysrepo-plugind: no-manual-page usr/bin/sysrepo-plugind
Why is this needed if the manual page is now included?

2021-12-13 08:21 UTC, michalvasko commented on distro/pkg/deb/sysrepo-tools.lintian-overrides
> +sysrepo: no-manual-page usr/bin/sysrepoctl
The manual pages are included, what is the purpose of this then?

2022-07-27 08:38 UTC, fbezdeka commented
On a clean environment (sbuilder) I saw the following when trying to build debian packages:

```
| dh_install: warning: Cannot find (any matches for) "usr/lib/systemd/system/sysrepo-plugind.service" (tried in ., debian/tmp)
```

cmake was unable to locate the systemd unit directory (cmake variable SYSTEMD_UNIT_DIR) and failed to install the systemd service file.

I fixed that by adding `systemd` to the build dependencies.

2022-07-28 13:58 UTC, michalvasko commented
Thanks but Debian scripts were not updated yet based on Fedora RPM review changes. We are hoping to finish RPMs soon and then the Debian scripts and packages will also be updated and officially submitted.

2022-12-15 10:51 UTC, closed without merging