ds json BUGFIX don't rename log files with old notification.
sysrepo/sysrepo pull request #3233
Opened 2024-01-24 10:52 UTC by jeremie6wind

sysrepo uses notification timestamps to rename the log files. The first timestamp in the name is the timestamp of the first notification and the second one is the timestamp of the last notification. However, if the timestamp is in the past, the new file name will be invalid. To avoid losing notification files, don't rename the file with an older timestamp. The file may contain notification with old timestamps.

2024-01-24 10:57 UTC, michalvasko commented
Could you please explain the problem in more detail? I do not get it. Maybe using an example.

2024-01-24 12:45 UTC, jeremie6wind commented
Yes, this can happen when you jump back in time. Ok I will replace the assert.

2024-01-24 12:59 UTC, michalvasko requested changes
Seems good now, thanks. Just please include a note in the comment that it can happen when there is a jump in realtime (because of NTP, for example).

2024-01-25 09:50 UTC, jeremie6wind commented
I have changed the comment as you suggested.

2024-01-25 10:12 UTC, michalvasko approved these changes

2024-01-25 10:13 UTC, michalvasko commented
Alright, thanks.

2024-01-25 10:13 UTC, merged